---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: local-cluster-amq-broker-development
  namespace: acm-subscriptions
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: managed/amq-broker/overlays/local-cluster
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: local-cluster-amq-broker-development
spec:
  channel: acm-configuration/acm-applications
  placement:
    placementRef:
      name: local-cluster-amq-broker-development
      kind: PlacementRule