apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: amq-broker-instance
  namespace: demo-amq-dc
spec:
  acceptors:
    - port: 5672
      verifyHost: false
      wantClientAuth: false
      expose: true
      needClientAuth: false
      multicastPrefix: /topic/
      name: amqp
      sslEnabled: false
      sniHost: localhost
      enabledProtocols: 'TLSv1,TLSv1.1,TLSv1.2'
      protocols: amqp
      sslProvider: JDK
      anycastPrefix: jms.queue.
  adminPassword: admin
  adminUser: admin
  console:
    expose: true
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 512Mi
    messageMigration: false
    managementRBACEnabled: true
    journalType: nio
    enableMetricsPlugin: true
    jolokiaAgentEnabled: false
    image: placeholder
    storage:
      size: 2Gi
  upgrades:
    enabled: false
    minor: false
  version: 7.9.4
status:
  podStatus:
    ready:
      - amq-broker-instance-ss-0
