---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: sno-dc-broker-development
  namespace: acm-subscriptions
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: sno-dc-broker-development